# Generated by Django 5.2.4 on 2025-08-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroupMember', to='groups.group'),
        ),
    ]
