# Generated by Django 5.2.4 on 2025-08-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_user_id_groupmember_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group'),
        ),
    ]
